### PR TITLE
Implement multiversion building for the docs

### PR DESCRIPTION
**Pull request by mschmidt87**
Use sphinx-multiversion instead of sphinx-build
Configure multiversion builds in docs conf file
Use RTD theme because it supports multiversion, remove msmb_theme
Add sphinx-multiversion to requirements

### CODE REVIEW

**Comment by jakobj** [comment]
great, thanks for working on this! :rocket: 

hmm, can i somehow look at the doc output? also, there's an error in the build:

```bash
make: Entering directory '/home/runner/work/hal-cgp/hal-cgp/docs'
sphinx-multiversion -D reset_argv=1 . _build/html
unknown config value 'reset_argv' in override, ignoring
No matching refs found!
make: *** [Makefile:32: html-examples-short] Error 2
make: Leaving directory '/home/runner/work/hal-cgp/hal-cgp/docs'
Error: Process completed with exit code 1.
```

**Comment by mschmidt87** [comment]
There are currently two problems:
- Generating the docs on my local machine gets stuck in one example (multi_genome) for the 0.2.0 release version. I don't understand why because running the example manually works seamlessly. I suspect that it has something to do with the multiprocessing in combination with subprocesses used by sphinx-multiversion, but I don't know how to test it or fix it.
- I don't know how to fix that issue in the CI. I had opened an issue about this (back when we were still using Travis) and received a reply from another user which I implemented but it doesn't help: https://github.com/Holzhaus/sphinx-multiversion/issues/57

So, I am leaning towards migrating the docs to readthedocs, which offers multiversion and does all the work for us.

**Comment by jakobj** [comment]
> There are currently two problems:
> 
>     * Generating the docs on my local machine gets stuck in one example (multi_genome) for the 0.2.0 release version. I don't understand why because running the example manually works seamlessly. I suspect that it has something to do with the multiprocessing in combination with subprocesses used by sphinx-multiversion, but I don't know how to test it or fix it.

hmm, `n_processes` is `1` in the example, so multiprocessing shouldn't be used. to tackle such issues, would it be worthwhile to implement a debug switch that disables multiprocessing across the whole library?

>     * I don't know how to fix that issue in the CI. I had opened an issue about this (back when we were still using Travis) and received a reply from another user which I implemented but it doesn't help: [Holzhaus/sphinx-multiversion#57](https://github.com/Holzhaus/sphinx-multiversion/issues/57)

ouch, i have no idea, sorry. can you reproduce the issue locally or does it only happen in CI?
 
> So, I am leaning towards migrating the docs to readthedocs, which offers multiversion and does all the work for us.

you have my blessing :)

**Comment by mschmidt87** [comment]
> > There are currently two problems:
> > ```
> > * Generating the docs on my local machine gets stuck in one example (multi_genome) for the 0.2.0 release version. I don't understand why because running the example manually works seamlessly. I suspect that it has something to do with the multiprocessing in combination with subprocesses used by sphinx-multiversion, but I don't know how to test it or fix it.
> > ```
> 
> hmm, `n_processes` is `1` in the example, so multiprocessing shouldn't be used. to tackle such issues, would it be worthwhile to implement a debug switch that disables multiprocessing across the whole library?
> 

This does not happen in CI, though, so seems to have something to do with my local system.

> > ```
> > * I don't know how to fix that issue in the CI. I had opened an issue about this (back when we were still using Travis) and received a reply from another user which I implemented but it doesn't help: [Holzhaus/sphinx-multiversion#57](https://github.com/Holzhaus/sphinx-multiversion/issues/57)
> > ```
> 
> ouch, i have no idea, sorry. can you reproduce the issue locally or does it only happen in CI?
Only in CI, so basically impossible to debug.
> 
> > So, I am leaning towards migrating the docs to readthedocs, which offers multiversion and does all the work for us.
> 
> you have my blessing :)


Yep, I will close this PR and open another one to migrate to readthedocs.

**Pull request closed without merging**
